setup-bash:
	python -m venv venv
	.venv/bin/activate
	pip install --upgrade pip
	pip install -r requirements.txt

setup-win-cmd:
	python -m venv venv
	.venv\Scripts\activate
	pip install --upgrade pip
	pip install -r requirements.txt

setup-win-pwsh:
	python -m venv venv
	.venv\Scripts\Activate.ps1
	pip install --upgrade pip
	pip install -r requirements.txt

freeze:
	pip freeze > requirements.txt

run-vertex:
	./src/VERTEX/run_local.sh

clean-all:
	@echo "Cleaning up Factory Monitoring System..."
	@echo "This will remove all containers, networks, and volumes!"
	@read -p "Are you sure? [y/N] " confirm && [ "$$confirm" = "y" ] || exit 1
	-@docker compose down -v
	-@docker system prune -f
	-@docker stop $$(docker ps -aq)
	-@docker rm $$(docker ps -aq)
	-@docker rmi $$(docker images -q)
	-@docker volume rm $$(docker volume ls -q)
	-@docker builder prune
	@echo "Cleanup completed!"

open-sql:
	psql -h localhost -p 5432 postgres

enter-docker:
	docker exec -it vertex sh